### ISSUE TITLE
Explore options for adding some basic search

### ISSUE THREAD

**Issue by outten45** [vivo-community/product-evolution-sandbox#26]
Explore options for handling search. A few things to answer:

- how to best index documents in elastic?
- should search be done through graphql?
- should their be a separate process for search indexing?

**Comment by jimwood** [comment]
* how to best index documents in elastic?
Use keywords for aggregations
* should search be done through graphql?
Yes
* should their be a separate process for search indexing?
TBD - depends on VIVO core
