### ISSUE TITLE
Make educations and affiliations (and possibly other things) part of person index

### ISSUE THREAD

**Issue by nymbyl** [vivo-community/product-evolution-sandbox#40]
since they are *only* related to a person, and see we don't want to return them as separate search items with separate entity pages - might make sense to add them to person index documents - might be able to use elastic "partial update" to keep idea of only updating what's changed

**Comment by outten45** [comment]
hi @nymbyl sounds mostly good to me. I'm not sure the separating or combining hurts this use case, but if in the future we wanted to pull a list of all people that got a degree from a particular institution, but that still be possible? I think it would be filtering on the educations in the user. 

I guess another way to look at it, could we see the list of institutions that we care about and then see the people associated with a particular institution?

**Comment by nymbyl** [comment]
I think the institutions would come in (later) in their own index - so I'm pretty sure both those would be possible.  The only thing it fixes now is making it easier for a search on the index to not return "educations" and "affiliations" as separate documents. You could also suppress that output, and make a separate query/join on the person documents based on personId - but this seemed more natural to me.  I don't know.

**Comment by outten45** [comment]
sounds good to me. thanks for the explanation!
